import Head from 'next/head';
import ContractView from '../components/ContractView';
import ExplainText from '../components/ExplainText';
import { WalletSelectorContextProvider } from '../components/WalletSelectorContext';

type Props = {
  network: 'testnet' | 'mainnet';
  contractName: string;
};
export default function Home({ network, contractName }: Props) {
  return (
    <>
      <Head>
        <title>React Boilerplate Template</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="relative flex min-h-screen flex-col justify-center overflow-hidden bg-gray-50 py-6 sm:py-12">
          <div className="absolute inset-0 [mask-image:linear-gradient(180deg,white,rgba(255,255,255,0))]"></div>
          <WalletSelectorContextProvider network={network} createAccessKeyFor={contractName}>
            <ContractView contractName={contractName} />
          </WalletSelectorContextProvider>
          <ExplainText />
        </div>
      </main>
    </>
  );
}

Home.getInitialProps = async () => {
  const contractName = process.env.NEXT_PUBLIC_CONTRACT_NAME!;
  const network = process.env.NEXT_PUBLIC_NEAR_NETWORK!;
  return { network, contractName };
};
